### ISSUE TITLE
Cannot read properties of undefined when copying the primitives

### ISSUE THREAD

**Issue by benjaminforras** [goetzrobin/spartan#34]
### Please provide the environment you discovered this bug in.

Created an NX based AnalogJS project with the defaults and added the UI components as described in the docs.s

### Which area/package is the issue in?

Don't know / other

### Description

When I wanted to copy the primitives it gave me an error. It is the same if I choose all (or select every option I'd like)

### Please provide the exception or error you saw

```true
√ Choose which primitives you want to copy · accordion, alert, alertdialog, aspectratio, avatar, badge, button, card, command, dialog, icon, input, label, menu, popover, progress, radiogroup, scrollarea, separator, sheet, skeleton, spinner, switch, tabs, toggle, typography, table, hovercard, collapsible, menubar, contextmenu

√ Some of the primitives you are trying to install depend on the icon primitive. Do you want to add it to your project? (Y/n) · true  
√ Some of the primitives you are trying to install depend on the button primitive. Do you want to add it to your project? (Y/n) · true
√ The context menu is implemented as part of the menu-helm primitive. Adding menu primitive. (y/N) · true
√ The menubar is implemented as part of the menu-helm primitive. Adding menu primitive. (y/N) · true

 >  NX   Cannot read properties of undefined (reading 'internalName')  


TypeError: Cannot read properties of undefined (reading 'internalName')
    at C:\Users\Shadow\Documents\Projects\thd\node_modules\@spartan-ng\nx\src\generators\ui\generator.js:44:68
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\Shadow\Documents\Projects\thd\node_modules\tslib\tslib.js:166:62)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [X] No

**Comment by goetzrobin** [comment]
Taking a look! Thanks for reporting this!

**Comment by goetzrobin** [comment]
@benjaminforras this should be fixed with the newest release of alpha 315

**Comment by benjaminforras** [comment]
```
tryharddood@SHADOW-TG1OJ07U:~/Projects/aiis$ npx nx g @spartan-ng/nx:ui --verbose

>  NX  Generating @spartan-ng/nx:ui

✔ Choose a directory to place your spartan libraries, e.g. libs/ui · libs/ui
? Choose which primitives you want to copy …
? Choose which primitives you want to copy …
✔ Choose which primitives you want to copy · all

 >  NX   Cannot read properties of undefined (reading 'internalName')


TypeError: Cannot read properties of undefined (reading 'internalName')
    at /home/tryharddood/Projects/aiis/node_modules/@spartan-ng/nx/src/generators/ui/generator.js:48:68
    at Generator.next (<anonymous>)
    at fulfilled (/home/tryharddood/Projects/aiis/node_modules/tslib/tslib.js:166:62)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

Sadly it's still the same with alpha-315

**Comment by goetzrobin** [comment]
Checking it out now

**Comment by benjaminforras** [comment]
I created a workspace with npx create-nx-workspace@latest, choose the monorepo type with an Angular app.
Installed tailwind with nx/angular generator.
Then I followed the instructions from the spartan.ng documentation site.
And then the issue happened again with the npx nx g @spartan-ng/nx:ui command

**Comment by goetzrobin** [comment]
Okay I will try to reproduce and fix now

**Comment by goetzrobin** [comment]
Just released alpha 316. Should work now

**Comment by benjaminforras** [comment]
It works fine! Thank you!
